import plugin from "tailwindcss/plugin";
import { themes } from "./themes.js";
import { semanticUtilities } from "./semanticUtilities.js";
import button from "./components/button.js";
import card from "./components/card.js";
import badge from "./components/badge.js";
import input from "./components/input.js";
import modal from "./components/modal.js";
import navbar from "./components/navbar.js";
import drawer from "./components/drawer.js";
import tabs from "./components/tabs.js";
import alerts from "./components/alerts.js";
import accordion from "./components/accordion.js";
import tooltip from "./components/tooltip.js";
import progress from "./components/progress.js";
import rating from "./components/rating.js";
import slider from "./components/slider.js";
import avatar from "./components/avatar.js";
import chip from "./components/chip.js";
import breadcrumb from "./components/breadcrumb.js";
import table from "./components/table.js";
import utilities from "./utilities.js";
import forms from "./components/forms.js";
import dropdown from "./components/dropdown.js";
import divider from "./components/divider.js";
import pagination from "./components/pagination.js";
import skeleton from "./components/skeleton.js";
import steps from "./components/steps.js";
import stats from "./components/stats.js";
import timeline from "./components/timeline.js";
import popover from "./components/popover.js";
import carousel from "./components/carousel.js";
import fileUpload from "./components/fileUpload.js";
import datePicker from "./components/datePicker.js";
import emptyState from "./components/emptyState.js";
import confirmDialog from "./components/confirmDialog.js";
import menu from "./components/menu.js";
import commandPalette from "./components/commandPalette.js";
import treeView from "./components/treeView.js";
import colorPicker from "./components/colorPicker.js";
import tagInput from "./components/tagInput.js";
import multiSelect from "./components/multiSelect.js";
import calendar from "./components/calendar.js";
import timePicker from "./components/timePicker.js";
import dataGrid from "./components/dataGrid.js";
import sidebarNav from "./components/sidebarNav.js";
import backdrop from "./components/backdrop.js";
import rangeInput from "./components/rangeInput.js";
import tabsVertical from "./components/tabsVertical.js";
import notification from "./components/notification.js";
import kbd from "./components/kbd.js";
import fab from "./components/fab.js";
import sheet from "./components/sheet.js";
export default plugin(function ({ addBase, addComponents, addUtilities }) {
  // 1) base variables + themes
  addBase(themes);

  // 2) components
  addComponents(button());
  addComponents(card());
  addComponents(badge());
  addComponents(input());
  addComponents(modal());
  addComponents(navbar());
  addComponents(drawer());
  addComponents(tabs());
  addComponents(alerts());
  addComponents(accordion());
  addComponents(tooltip());
  addComponents(progress());
  addComponents(rating());
  addComponents(slider());
  addComponents(avatar());
  addComponents(chip());
  addComponents(breadcrumb());
  addComponents(table());
  addComponents(forms());
  addComponents(dropdown());
  addComponents(divider());
  addComponents(pagination());
  addComponents(skeleton());
  addComponents(steps());
  addComponents(stats());
  addComponents(timeline());
  addComponents(popover());
  addComponents(carousel());
  addComponents(fileUpload());
  addComponents(datePicker());
  addComponents(emptyState());
  addComponents(confirmDialog());
  addComponents(menu());
  addComponents(commandPalette());
  addComponents(treeView());
  addComponents(colorPicker());
  addComponents(tagInput());
  addComponents(multiSelect());
  addComponents(calendar());
  addComponents(timePicker());
  addComponents(dataGrid());
  addComponents(sidebarNav());
  addComponents(backdrop());
  addComponents(rangeInput());
  addComponents(tabsVertical());
  addComponents(notification());
  addComponents(kbd());
  addComponents(fab());
  addComponents(sheet());

  // 3) semantic utilities (colors, effects)
  addUtilities(semanticUtilities);

  // 4) extended utilities (animations, effects, etc.)
  addUtilities(utilities());
});
